package com.nova.ai.utils

import android.content.Context
import android.os.Environment
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.properties.TextAlignment
import com.nova.ai.models.CommandResult
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.apache.poi.xslf.usermodel.XMLSlideShow
import org.apache.poi.xslf.usermodel.XSLFSlideLayout
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class FileGenerator @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val downloadsDir = Environment
        .getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)

    private fun timestamp() = SimpleDateFormat("MMdd_HHmm", Locale.getDefault()).format(Date())

    // ─── PDF ───
    suspend fun generatePDF(title: String, content: String): CommandResult =
        withContext(Dispatchers.IO) {
            try {
                val file = File(downloadsDir, "NOVA_${title.take(20)}_${timestamp()}.pdf")
                val writer = PdfWriter(FileOutputStream(file))
                val pdf = PdfDocument(writer)
                val doc = Document(pdf)

                // Title
                doc.add(
                    Paragraph(title)
                        .setBold()
                        .setFontSize(22f)
                        .setFontColor(ColorConstants.DARK_GRAY)
                        .setTextAlignment(TextAlignment.CENTER)
                        .setMarginBottom(20f)
                )

                // Date
                doc.add(
                    Paragraph("Generated by NOVA AI · ${SimpleDateFormat("MMM dd, yyyy", Locale.getDefault()).format(Date())}")
                        .setFontSize(9f)
                        .setFontColor(ColorConstants.GRAY)
                        .setTextAlignment(TextAlignment.CENTER)
                        .setMarginBottom(30f)
                )

                // Content
                content.split("\n").filter { it.isNotBlank() }.forEach { line ->
                    doc.add(
                        Paragraph(line)
                            .setFontSize(12f)
                            .setMarginBottom(8f)
                    )
                }

                doc.close()
                scanFile(file)
                CommandResult.Success("PDF_SAVED:${file.absolutePath}\nPDF created: ${file.name}")
            } catch (e: Exception) {
                CommandResult.Error("PDF creation failed: ${e.message}")
            }
        }

    // ─── PPT ───
    suspend fun generatePPT(title: String, content: String): CommandResult =
        withContext(Dispatchers.IO) {
            try {
                val file = File(downloadsDir, "NOVA_${title.take(20)}_${timestamp()}.pptx")
                val ppt = XMLSlideShow()

                // Title slide
                val titleLayout = ppt.slideLayouts.firstOrNull() ?: ppt.slideLayouts[0]
                val slide1 = ppt.createSlide(titleLayout)
                slide1.placeholders.forEachIndexed { i, ph ->
                    when (i) {
                        0 -> ph.setText(title)
                        1 -> ph.setText("Generated by NOVA AI · ${SimpleDateFormat("MMM dd, yyyy", Locale.getDefault()).format(Date())}")
                    }
                }

                // Content slides — split every 5 bullet points
                val bullets = content.split("\n", ".").filter { it.isNotBlank() }.take(20)
                bullets.chunked(5).forEachIndexed { idx, chunk ->
                    val contentSlide = ppt.createSlide(titleLayout)
                    contentSlide.placeholders.forEachIndexed { i, ph ->
                        when (i) {
                            0 -> ph.setText("Slide ${idx + 2}: $title")
                            1 -> ph.setText(chunk.joinToString("\n• ", "• "))
                        }
                    }
                }

                FileOutputStream(file).use { ppt.write(it) }
                ppt.close()
                scanFile(file)
                CommandResult.Success("PPT_SAVED:${file.absolutePath}\nPresentation created: ${file.name}")
            } catch (e: Exception) {
                CommandResult.Error("PPT creation failed: ${e.message}")
            }
        }

    // ─── TXT ───
    suspend fun generateTXT(content: String): CommandResult =
        withContext(Dispatchers.IO) {
            try {
                val file = File(downloadsDir, "NOVA_Note_${timestamp()}.txt")
                val timestamp = SimpleDateFormat("EEE MMM dd, yyyy HH:mm", Locale.getDefault()).format(Date())
                file.writeText("NOVA AI Note\nSaved: $timestamp\n\n$content")
                scanFile(file)
                CommandResult.Success("TXT_SAVED:${file.absolutePath}\nNote saved: ${file.name}")
            } catch (e: Exception) {
                CommandResult.Error("Save failed: ${e.message}")
            }
        }

    private fun scanFile(file: File) {
        android.media.MediaScannerConnection.scanFile(
            context, arrayOf(file.absolutePath), null, null
        )
    }
}
